/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bg.uni_sofia.fmi.oopjava.windows;

import bg.uni_sofia.fmi.oopjava.enums.Permissions;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JCheckBox;

/**
 *
 * @author John
 */
public class AddRemoveUserPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddRemoveUserPanel
     */
    public AddRemoveUserPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddRemoveUserTitle = new javax.swing.JLabel();
        btnAddUser = new javax.swing.JButton();
        btnRemoveUser = new javax.swing.JButton();
        chkboxDecrypt = new javax.swing.JCheckBox();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblPermissions = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        chkboxEncrypt = new javax.swing.JCheckBox();
        txtPassword = new javax.swing.JPasswordField();

        lblAddRemoveUserTitle.setText("Add / Remove User");

        btnAddUser.setText("Add");
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });

        btnRemoveUser.setText("Remove");

        chkboxDecrypt.setText("Decrypt");

        lblUsername.setText("Username");

        lblPassword.setText("Password");

        lblPermissions.setText("Permissions");

        chkboxEncrypt.setText("Encrypt");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUsername)
                                    .addComponent(lblPassword)
                                    .addComponent(lblPermissions))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(chkboxEncrypt)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnRemoveUser, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(chkboxDecrypt)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))))
                            .addComponent(lblAddRemoveUserTitle)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAddRemoveUserTitle)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPermissions)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chkboxEncrypt)
                        .addComponent(chkboxDecrypt)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddUser)
                    .addComponent(btnRemoveUser))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed

    }//GEN-LAST:event_btnAddUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnRemoveUser;
    private javax.swing.JCheckBox chkboxDecrypt;
    private javax.swing.JCheckBox chkboxEncrypt;
    private javax.swing.JLabel lblAddRemoveUserTitle;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPermissions;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    public JButton[] getButtons() {
        JButton[] buttons = new JButton[2];
        buttons[0] = btnAddUser;
        buttons[1] = btnRemoveUser;
        return buttons;
    }

    public String getUsernameText() {
        return txtUsername.getText();
    }

    public String getPasswordText() {
        return new String(txtPassword.getPassword());
    }

    public JCheckBox[] getPermissionsBoxes() {
        JCheckBox[] permissionsBoxes = new JCheckBox[2];
        permissionsBoxes[0] = chkboxEncrypt;
        permissionsBoxes[1] = chkboxDecrypt;
        return permissionsBoxes;
    }

    public Permissions[] getPermissions() {
        JCheckBox[] permissionsBoxes = getPermissionsBoxes();
        ArrayList<Permissions> permissions = new ArrayList<>();
        if (permissionsBoxes[0].isSelected()) {
            permissions.add(Permissions.ENCRYPT);
        }
        if (permissionsBoxes[1].isSelected()) {
            permissions.add(Permissions.DECRYPT);
        }
        Permissions[] permissionsArray = new Permissions[permissions.size()];
        permissions.toArray(permissionsArray);
        return permissionsArray;
    }
}
